### ISSUE TITLE
no protocol issue

### ISSUE THREAD

**Issue by mis3250** [himukr/google-grp-scraper#2]
HI Himukr:

Please discard my previous message. Here is the revised question.

I have tried your java code and got the following error. Compilation is fine.

C:\maven\googleGroup\google-grp-scraper\target>java -jar google-grp-scraper-0.0.
1-SNAPSHOT.jar 'https://groups.google.com/forum/#!forum/ibm.software.websphere.a
pplication-server' 20
Exception in thread "main" java.net.MalformedURLException: no protocol: 'https:/
/groups.google.com/forum/#!forum/ibm.software.websphere.application-server'
at java.net.URL.(Unknown Source)
at java.net.URL.(Unknown Source)
at java.net.URL.(Unknown Source)
at com.pramati.scraper.google_grp_scraper.ScraperStartup.main(ScraperSta
rtup.java:9)

Would you please take a look. Does URL class have some bugs?

Thanks.

**Comment by DavidLeoni** [comment]
The problem is that URL class is getting the url WITH the quotes, because the command line in windows is passing them to the program. To avoid this, wrap the url in double quotes instead. So this should do:

```
java -jar google-grp-scraper-0.0.1-SNAPSHOT.jar "https://groups.google.com/forum/#!forum/ibm.software.websphere.application-server"  20
```
